import "@/styles/global.scss";
import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';
import { gilroy, inter } from './fonts/fonts';
import { Suspense } from 'react';

export const metadata = {
  title: "HRWC | Home",
  description: "Generated by create next app",
  // icons: [
  //   {
  //     url: '/favicon.png',
  //   },
  // ],
  // openGraph: {
  //   title: 'HRWC',
  //   description: 'OG Description',
  //   images: [
  //     {
  //       url: '/ogp.jpg',
  //     },
  //   ],
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${gilroy.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
